image: registry.cn-hangzhou.aliyuncs.com/codeages/android-ci:3.0.6

stages:
- build

build:
  stage: build
  script:
    - cd EduSohoAndroidClient/kuozhiv2
    - gradle build -x lint
    - gradle copyApk
  artifacts:
    paths:
    - EduSohoAndroidClient/kuozhiv2/outputs
    expire_in: 1 week
  only:
    - develop
    - master
    

