image: li7tlemk/edusoho-android-ci:3.0.4

build:
  script:
    - cd EduSohoAndroidClient/kuozhiv2
    - gradle build
    - gradle copyApk
  artifacts:
    paths:
    - EduSohoAndroidClient/kuozhiv2/outputs
