image: li7tlemk/edusoho-android-ci:2.14.1

build:
  script:
    - ./EduSohoAndroidClient/gradlew assembleRelease --build-file ./EduSohoAndroidClient/kuozhiv2/build.gradle
  artifacts:
    paths:
    - ./EduSohoAndroidClient/outputs
